global:
  zeebe: "{{ .Release.Name }}-zeebe"

image:
  repository: camunda/zeebe
  tag: 1.3.3
  pullPolicy: IfNotPresent  

tasklist:
  enabled: false

# Zeebe configuration
# for available values see `helm show values zeebe/zeebe-cluster-helm`
# or https://github.com/camunda-community-hub/camunda-cloud-helm/tree/main/charts/zeebe-cluster-helm
#zeebe-cluster-helm:
clusterSize: "1"
partitionCount: "1"
replicationFactor: "1"

elasticsearch:
  enabled: false
