apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: jetstream-broker
  namespace: nats
  annotations:
    eventing.knative.dev/broker.class: MTChannelBasedBroker
spec:
  config:
    apiVersion: v1
    kind: ConfigMap
    name: config-natjsm-channel
    namespace: nats
